# Generated by Django 4.1.13 on 2024-04-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.CharField(default='No Description', max_length=1000),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
