# Generated by Django 4.1.13 on 2024-04-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0002_dish_category_dish_description_dish_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='image',
            field=models.ImageField(default='default_dish.jpg', upload_to='dishes/'),
        ),
    ]
