# Generated by Django 4.1.13 on 2024-05-22 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CafeApp', '0008_remove_order_dishes_alter_order_user_orderdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
